modlr_auth_bundle_user_create:
    path: /auth/user/create
    defaults: { _controller: Limit0ModlrAuthBundle:Auth:userCreate }
    methods: [ POST ]

modlr_auth_bundle_user_destroy:
    path: /auth/user/destroy

modlr_auth_bundle_user_retrieve:
    path: /auth/user/retrieve
    defaults: { _controller: Limit0ModlrAuthBundle:Auth:userRetrieve }

modlr_auth_bundle_user_submit:
    path: /auth/user/submit
    methods: [ POST ]
