services:

    modlr_auth_bundle.security.auth.generator_manager:
        class: Limit0\ModlrAuthBundle\Security\Auth\AuthGeneratorManager
        calls:
            - [ addGenerator, [ "@modlr_auth_bundle.security.auth.generator.core_user" ] ]

    modlr_auth_bundle.security.auth.generator.core_user:
        private: true
        class: Limit0\ModlrAuthBundle\Security\Auth\CoreUserGenerator
        arguments: [ "@modlr_auth_bundle.security.jwt.generator_manager", "@request_stack" ]

    modlr_auth_bundle.security.authenticator.api:
        parent: modlr_auth_bundle.security.authenticator.core_user.abstract
        class: Limit0\ModlrAuthBundle\Security\Authenticator\ApiAuthenticator
        arguments: [ "@as3_modlr.api.adapter", "@security.http_utils", "@modlr_auth_bundle.security.jwt.generator_manager" ]
        calls:
            - [ addRoute, [ "as3_modlr_rest_api" ] ]

    modlr_auth_bundle.security.authenticator.core_user:
        parent: modlr_auth_bundle.security.authenticator.core_user.abstract
        class: Limit0\ModlrAuthBundle\Security\Authenticator\CoreUserAuthenticator
        arguments: [ "@as3_modlr.api.adapter", "@security.http_utils", "@security.encoder_factory", "@modlr_auth_bundle.security.auth.generator_manager" ]
        calls:
            - [ addRoute, [ "modlr_auth_bundle_user_submit" ] ]

    modlr_auth_bundle.security.authenticator.core_user.abstract:
        private: true
        abstract: true

    modlr_auth_bundle.security.jwt.generator_manager:
        private: true
        class: Limit0\ModlrAuthBundle\Security\JWT\JWTGeneratorManager
        calls:
            - [ addGenerator, [ "@modlr_auth_bundle.security.jwt.generator.core_user" ] ]

    modlr_auth_bundle.security.jwt.generator.core_user:
        private: true
        class: Limit0\ModlrAuthBundle\Security\JWT\CoreUserGenerator
        arguments: [ "%limit0_modlr_auth.jwt.secret%", "%limit0_modlr_auth.jwt.issuer%", "%limit0_modlr_auth.jwt.ttl%" ]

    modlr_auth_bundle.security.login_listener:
        private: true
        class: Limit0\ModlrAuthBundle\Security\LoginListener
        arguments: [ "@security.authorization_checker", "@as3_modlr.store" ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    modlr_auth_bundle.security.logout_success_handler:
        private: true
        class: Limit0\ModlrAuthBundle\Security\LogoutSuccessHandler
        arguments: [ "@modlr_auth_bundle.security.auth.generator_manager" ]

    modlr_auth_bundle.security.user_provider.core_user:
        private: true
        class: Limit0\ModlrAuthBundle\Security\User\CoreUserProvider
        arguments: [ "@as3_modlr.store", "@request_stack" ]

    modlr_auth_bundle.command.user.create:
        private: true
        class: Limit0\ModlrAuthBundle\Command\User\CreateUserCommand
        arguments: [ "@as3_modlr.store" ]
        tags:
            - { name: "console.command"}

    modlr_auth_bundle.command.account.create:
        private: true
        class: Limit0\ModlrAuthBundle\Command\Account\CreateAccountCommand
        arguments: [ "@as3_modlr.store" ]
        tags:
            - { name: "console.command"}

    modlr_auth_bundle.event_subscriber.core_user:
        private: true
        class: Limit0\ModlrAuthBundle\EventSubscriber\CoreUserSubscriber
        arguments: [ "@security.password_encoder" ]
        tags:
            - { name: as3_modlr.event_subscriber }
